#!/bin/perl

sub listwindows {
  open(IN, "dbus-send --session --print-reply --dest=org.wmaker.WMServer /org/wmaker/WMDesktop org.wmaker.WMInterface.GetWindows string:0 |");

  my $el = 0;
  my $winid = "";
  my $wititle = "";
  my $winflag = "";

  while(<IN>) {
    chomp();
    if ($_ =~ /^\s*struct {/) {
      $el = 1;
    }
    elsif ($_ =~ /^\s*}$/ && $el) {
      print("$winflag\t$winid\t$wintitle\n");

      $el = 0;
    }
    elsif ($_ =~ m/^\s+string \"(.*?)\"$/) {
      $winid    = $1 if ($el == 1);
      $wintitle = $1 if ($el == 2);
      $winflag  = $1 if ($el == 3);

      $el++;
    }
  }

  close(IN);
}

sub activate {
  my ($winid) = @_;
  system("dbus-send --session --print-reply --dest=org.wmaker.WMServer /org/wmaker/WMDesktop org.wmaker.WMInterface.ActivateWindow string:$winid");
}

sub usage {
  print(STDERR "wmcmd --list | --activate\n");
  exit 1;
}

if ($ARGV[0] eq "" || $ARGV[0] eq "--help") {
 usage();
}
elsif ($ARGV[0] eq "--list") {
  listwindows();
}
elsif ($ARGV[0] eq "--activate" && $ARGV[1] ne "") {
  activate($ARGV[1]);
}
else {
  usage();
}
